# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Plotting Pretty Projects
email: story645@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A slightly rambling how to guide on diving into the 
  somewhat overwhelming and sometimes confusing world of 
  contributing to matplotlib. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://story645.github.io/" # the base hostname & protocol for your site
twitter_username: story645
github_username:  story645
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
